### ISSUE TITLE
Post created_at  is incorrect

### ISSUE THREAD

**Issue by philduffy** [artisan-tattoo/assistant-api#23]
Seems that one of the pitfalls of using the file system approach is that there's no way to store the created_at in a way that's accessible by Rails. I see you used ctime, but that's based off of when the file is written to the filesystem, not it's actual creation date. My assumption is that every time you deploy it will clobber the ctime of the file with the deploy time. (Note this is completely unsubstantiated and a complete guess).

I worry about not having a proper creation time and how that will affect RSS (Spoiler: maybe not at all).

Overall, this is generally a non-issue, but I think it's an interesting situation to think about. One solution I have would be a pattern similar to this:

http://harpjs.com/recipes/wrap-markdown-posts

Couldn't find a direct rails based parallel, but I think the idea would translate. Also, might be a bit heavier than what you want to deal with for solving a bogus created_at :P

EDIT: Had the thought that a lightweight solution would be to put a timestamp in the filename generated by to_s(:number)

```ruby
irb(main):010:0> Time.now.to_s(:number)
=> "20140618002121"
```

You could then parse that out via regex or filename.to_s.last(14)

**Comment by steveklabnik** [comment]
now that this is in node this doesn't matter
