### ISSUE TITLE
build trouble

### ISSUE THREAD

**Issue by dackdel** [artisan-tattoo/assistant-api#56]
https://www.dropbox.com/s/m265cfzudg4je3p/Screenshot%202015-07-06%2012.25.40.png?dl=0

when i type in npm start i get ^ that error. am I doing something wrong?

**Comment by steveklabnik** [comment]
I can't be sure what the error is, this isn't quite enough. See that last line of the screenshot, about the file to include? Can you share that?

**Comment by steveklabnik** [comment]
ah, i figured it out. one minute
